# Generated by Django 6.1 on 2026-09-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_profile_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='public',
        ),
    ]
